// Copyright 2019 Google, Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package structeditor

import (
	"fmt"
	"net/http"
)

// Handlers for serving the view interface via HTTP and handling mutation requests

// ViewHandler is an HTTP request handler that returns the structeditor user
// interface.
func (e *editor) ViewHandler(w http.ResponseWriter, r *http.Request) {
	result, err := e.Render()
	if err != nil {
		http.Error(w, err.Error(), 500)
	} else {
		w.Header().Set("Content-Type", "text/html")
		fmt.Fprintf(w, "%s", result)
	}
}

// MutateHandler is an HTTP request handler that modifies the editable state in
// response to mutation operations (usually generated by the UI built by
// ViewHandler).
func (e *editor) MutateHandler(w http.ResponseWriter, r *http.Request) {
	values := r.URL.Query()
	path := values.Get("path")
	operator, err := e.OperatorFor(values)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	err = e.Mutate(path, operator)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	http.Error(w, "", 200)
}
